// Auto-syncs src/version.js from package.json — single source of truth.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf8"));
const target = resolve(root, "src/version.js");

const banner = "// AUTO-GENERATED by scripts/sync-version.js. Do not edit.\n";
const content = `${banner}export const VERSION = ${JSON.stringify(pkg.version)};\n`;

writeFileSync(target, content);
console.log(`synced version: ${pkg.version} -> src/version.js`);
